In [1]:
#Write a NumPy program to create a 3x3 matrix with values ranging from 2 to 10.
import numpy as np

In [4]:
np.array(np.arange(2,11)).reshape(3,3)

array([[ 2,  3,  4],
       [ 5,  6,  7],
       [ 8,  9, 10]])

In [5]:
#Write a NumPy program to create an array with values ranging from 12 to 38.
np.array(np.arange(12,39))

array([12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28,
       29, 30, 31, 32, 33, 34, 35, 36, 37, 38])

In [6]:
#Write a NumPy program to reverse an array (first element becomes last).
arr1 = np.array(np.arange(12,39))
print(arr1)
print(arr1[::-1])

[12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33 34 35
 36 37 38]
[38 37 36 35 34 33 32 31 30 29 28 27 26 25 24 23 22 21 20 19 18 17 16 15
 14 13 12]


In [44]:
#Write a NumPy program to create a 2d array with 1 on the border and 0 inside.
arr = np.ones((5,5))

In [46]:
arr[1:-1,1:-1] = 0
arr

array([[1., 1., 1., 1., 1.],
       [1., 0., 0., 0., 1.],
       [1., 0., 0., 0., 1.],
       [1., 0., 0., 0., 1.],
       [1., 1., 1., 1., 1.]])

In [47]:
#Write a NumPy program to add a border (filled with 0's) around an existing array.
arr = np.zeros((5,5))
arr[1:-1,1:-1] = 1
arr

array([[0., 0., 0., 0., 0.],
       [0., 1., 1., 1., 0.],
       [0., 1., 1., 1., 0.],
       [0., 1., 1., 1., 0.],
       [0., 0., 0., 0., 0.]])

In [51]:
#Write a NumPy program to create a 8x8 matrix and fill it with a checkerboard pattern.
arr = np.ones((8,8))
arr[::2,::2] = 0
arr

array([[0., 1., 0., 1., 0., 1., 0., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1.],
       [0., 1., 0., 1., 0., 1., 0., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1.],
       [0., 1., 0., 1., 0., 1., 0., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1.],
       [0., 1., 0., 1., 0., 1., 0., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1.]])

In [52]:
#Write a NumPy program to convert the values of Centigrade degrees into Fahrenheit degrees.
#Centigrade values are stored into a NumPy array.
#Sample Array [0, 12, 45.21 ,34, 99.91]   (0°C × 9/5) + 32 = 32°F

arr = np.array([0, 12, 45.21 ,34, 99.91])
(arr*9/5)+32

array([ 32.   ,  53.6  , 113.378,  93.2  , 211.838])

In [61]:
#Write a NumPy program to test whether each element of a 1-D array is also present in a secondarray.
arr1 = np.array([0,10,30,40,60])
arr2 = np.array([10,40])
np.in1d(arr1,arr2)

array([False,  True, False,  True, False])

In [60]:
#Write a NumPy program to find the set difference of two arrays. The set difference will return the
#sorted, unique values in array1 that are not in array2.
arr1 = np.array([0,10,30,40,60])
arr2 = np.array([10,40])
np.setdiff1d(arr1,arr2)

array([ 0, 30, 60])

In [62]:
#Write a NumPy program to find the set exclusive-or of two arrays. Set exclusive-or will return the
#sorted, unique values that are in only one (not both) of the input arrays.
arr1 = np.array([0,10,30,40,60])
arr2 = np.array([10,40])
np.setxor1d(arr1,arr2)

array([ 0, 30, 60])

In [64]:
#Write a NumPy program to compare two given arrays.
arr1 = np.array([1,2,3,4])
arr2 = np.array([3,4,5,6])
print(arr1>=arr2)

[False False False False]


In [65]:
print(arr1<=arr2)

[ True  True  True  True]


In [68]:
print(arr1==arr2)

[False False False False]


In [69]:
arr = np.array([[1,2,3],[4,5,6]])
print(arr)

[[1 2 3]
 [4 5 6]]


In [73]:
arr.tofile("arr1.txt",sep = " ",format="%d")

In [76]:
a1 = np.array(np.arange(0,10))
a1

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [77]:
a1.shape

(10,)

In [80]:
a2 = a1.reshape(2,5)
a2

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [81]:
a2.shape

(2, 5)

In [86]:
np.diag((1,2,3,4))

array([[1, 0, 0, 0],
       [0, 2, 0, 0],
       [0, 0, 3, 0],
       [0, 0, 0, 4]])

In [87]:
np.log((1,2,3,4))

array([0.        , 0.69314718, 1.09861229, 1.38629436])

In [91]:
a = np.array([10,10,20,10,20,20,20,30,30,50,40,40])
np.unique(a)

array([10, 20, 30, 40, 50])